# Generated by Django 5.0.4 on 2024-06-08 14:15

from django.db import migrations
from django.contrib.postgres.operations import CITextExtension


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        CITextExtension()
    ]
