# Generated by Django 5.0.3 on 2024-03-22 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='lease_end_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 21, 20, 46, 34, 811307, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='rental',
            name='lease_start_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 22, 20, 46, 34, 811307, tzinfo=datetime.timezone.utc)),
        ),
    ]
