# Generated by Django 5.0.3 on 2024-03-20 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_management', '0002_alter_rental_lease_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='lease_duration',
            field=models.DurationField(blank=True, default=datetime.timedelta(days=30), null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='lease_end_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 19, 19, 19, 57, 846436, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='rental',
            name='lease_start_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 20, 19, 19, 57, 846436, tzinfo=datetime.timezone.utc)),
        ),
    ]
