# Generated by Django 5.0.3 on 2024-03-22 20:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_management', '0002_alter_rental_lease_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='last_last',
            new_name='last_name',
        ),
        migrations.AlterField(
            model_name='rental',
            name='lease_end_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 21, 20, 47, 21, 626653, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='rental',
            name='lease_start_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 22, 20, 47, 21, 626653, tzinfo=datetime.timezone.utc)),
        ),
    ]
