# Generated by Django 5.0.3 on 2024-03-20 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_management', '0003_rental_description_alter_rental_lease_duration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referenceperson',
            old_name='last_last',
            new_name='last_name',
        ),
        migrations.AlterField(
            model_name='rental',
            name='lease_end_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 19, 19, 25, 48, 964674, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='rental',
            name='lease_start_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 20, 19, 25, 48, 964674, tzinfo=datetime.timezone.utc)),
        ),
    ]
