# Generated by Django 5.0.3 on 2024-03-20 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_management', '0004_rename_last_last_referenceperson_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='line2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='lease_end_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 19, 19, 34, 42, 86653, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='rental',
            name='lease_start_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 20, 19, 34, 42, 86653, tzinfo=datetime.timezone.utc)),
        ),
    ]
