# Generated by Django 5.0.3 on 2024-03-21 03:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_management', '0006_rename_rent_property_default_rent_rental_rental_freq_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='lease_end_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 20, 3, 55, 53, 256543, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='rental',
            name='lease_start_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 21, 3, 55, 53, 256543, tzinfo=datetime.timezone.utc)),
        ),
    ]
