# Generated by Django 5.0.3 on 2024-03-21 04:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_management', '0007_alter_rental_lease_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenceperson',
            name='email',
            field=models.EmailField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='lease_end_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 20, 4, 12, 22, 826026, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='rental',
            name='lease_start_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 21, 4, 12, 22, 826026, tzinfo=datetime.timezone.utc)),
        ),
    ]
