# Generated by Django 5.0.3 on 2024-03-21 04:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_management', '0008_alter_referenceperson_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='lease_end_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 20, 4, 13, 28, 455156, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='rental',
            name='lease_start_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 21, 4, 13, 28, 455156, tzinfo=datetime.timezone.utc)),
        ),
    ]
