# Generated by Django 5.0.3 on 2024-03-25 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_management', '0008_alter_rental_lease_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='lease_end_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 24, 6, 36, 28, 756340, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='rental',
            name='lease_start_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 25, 6, 36, 28, 756340, tzinfo=datetime.timezone.utc)),
        ),
    ]
